version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: nexusdb
  MYSQL_USER: user
  MYSQL_PASSWORD: pwd

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environments:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_HOST: localhost

nginx:
  depends on:
    - api
    - client
  restart: always
  build:
    dockerfile: Dockerfile
    context: ./nginx
  ports:
    - "3050:80"

api:
  build:
    dockerfile: Dockerfile
    context: "./server"
  depends_on:
    - mydql_db
  volumes:
    - /app/node_modules
    - ./server:/app
  environment:
    <<: *common-variables
    MYSQL_HOST_IP: mysql_db
  
client:
  stdin_open: true
  environment:
    - CHOKIDAR_USEPOLLING = true
  build:
    dockerfile: Dockerfile
    context: ./client
  volumes:
    - /app/node_modules
    - ./client:/app

adminer:
  image: adminer:latest
  restart: unless-stopped
  ports:
    - 8000:8080
  depends_on:
    - mysql_db
  environment:
    ADMINER_DEFAULT_SERVER: mysql_db
